### ISSUE TITLE
How can i create a translation?

### ISSUE THREAD

**Issue by wernerkrauss** [dnadesign/silverstripe-populate#10]
How can i create a translation with Translatable using populate? I mean, that it also generates the right entry in the translation_groups table...

**Comment by wernerkrauss** [comment]
Found it, this works for me on a clean database:

```
Page:
  foo:
    Title: Foo
    Locale: de_DE
  foo-en:
    Title: 'Foo EN'
    Locale: en_GB
    _TranslationGroupID: =>Page.foo
```
