### ISSUE TITLE
PopulateMergeMatch does not work as expected

### ISSUE THREAD

**Issue by nebucaz** [dnadesign/silverstripe-populate#15]
I expected to be able to update/merge existing records using PopulateMergeMatch as described in the documentation based. I've written a simple example like follows:

##_config/config.yml
```
Member:
  test:
    Email: "test@test.com"
    Password: "password"
    PopulateMergeMatch:
      - Email
```

I expected the Populate task to merge with the existing record on consecutive runs of the populate task but it throws a validation error:
```
ERROR [User Error]: Uncaught ValidationException: Can't overwrite existing member #1 with identical identifier (Email = test@test.com))
IN GET /dev/tasks/PopulateTask
Line 852 in framework/security/Member.php
```

I've posted the sample-project here https://github.com/nebucaz/sspopulate

**Comment by Leapfrognz** [comment]
The issue is that $obj = $blueprint->createObject($identifier, $data, $this->fixtures); actually writes the new object. This cant happen if the original being updated a unique index, such as Email with members. Unfortunately FixtureBlueprint is a core class.

**Comment by jakxnz** [comment]
Can confirm, this is effecting any record with a unique index duplicated by populate data

**Comment by jonom** [comment]
I hit this problem as well so I tried the example from the ReadMe:

```
SilverStripe\Security\Member:
  admin:
    ID: 1
    Email: "admin@example.com"
    PopulateMergeMatch:
      - 'ID'
      - 'Email'
```

It doesn't throw the same error but it also doesn't create a member. There is no Member with an ID of 1 or an email of admin@example.com.

I also get a `[Notice] Undefined index: MyRelationID` when trying to use a has_one in `PopulateMergeMatch`.

**Comment by matt-in-a-hat** [comment]
This also affects anything that has side effects when created, e.g. this will not work for Page because it'll try create a new page with the same `URLSegment` which updates the `URLSegment` on save, meaning you don't end up with the value you've told it to enter
```yml
Page:
  page1:
    Title: 'A page'
    URLSegment: 'a-page'
    PopulateMergeWhen: "URLSegment = 'a-page' AND ParentID = 0"
```
(despite this being an example on the readme - https://github.com/silverstripe/silverstripe-populate?tab=readme-ov-file#populatemergewhen)

Unless anyone has a better way of doing this?
