### ISSUE TITLE
How to add many_many relation?

### ISSUE THREAD

**Issue by wernerkrauss** [dnadesign/silverstripe-populate#9]
Could you please provide an example of how to format the yml to add some many_many relations?

**Comment by wernerkrauss** [comment]
Found it out. Comma seperated list like with test fixtures does the trick now.

```
TeamLanguage:
  de:
    Title: German
  en:
    Title: English
  cz:
    Title: Czech
TeamMember:
  foo:
    FirstName: 'Foo'
    Surname: 'Bar'
    Languages: =>TeamLanguage.de,=>TeamLanguage.cz
```
